---
# handlers file for node-exporter
- name: restart node_exporter
  systemd:
     name: "{{ serviceName }}"
     state: restarted
     daemon_reload: yes

- name: Reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload

