---
- name: add data source
  grafana_datasource:
    name: "{{ item.name }}"
    grafana_url: "{{ grafana_url }}"
    grafana_user: "{{ grafana_user }}"
    grafana_password: "{{ grafana_password }}"
    ds_type: "{{ item.ds_type }}"
    url: "{{ item.url }}"
    database: "{{ item.name }}"
    #user: "{{ item.user }}"
    #password: "{{ item.password }}"
    state: present
  with_items: "{{ data_source }}"
